### ISSUE TITLE
W: Possible missing firmware /lib/firmware/i915/skl_guc_ver6.bin for module i915_bpo

### ISSUE THREAD

**Issue by maravento** [linuxenko/ubuntu-skylake-i915-video-fix#12]
Ubuntu 16.04.1 LTS x64
Generating /boot/initrd.img-4.4.0-34-generic
W: Possible missing firmware /lib/firmware/i915/skl_guc_ver6.bin for module i915_bpo

**Comment by ulf1** [comment]
i had the same problem while updating a fresh Ubuntu 16.04
