### ISSUE TITLE
Ran install-config.sh from desktop, now can't start Linux Mint 18.2 normally

### ISSUE THREAD

**Issue by southhill773** [linuxenko/ubuntu-skylake-i915-video-fix#25]
So, first off, just know that I'm not a techie and have only been using a Linux distro (Mint) for about a month, now. Before that, I've had zero experience with Linux whatsoever.

So, I was having a problem with VLC today and found this forum page here by a guy having the exact same problem: https://forums.linuxmint.com/viewtopic.php?f=47&t=233740

As you can see, this guy fixed his issue by using the fix here. Well, I decided to do the same and so I downloaded the fix and ran install-config.sh while it was in desktop without copying 20-intel.conf from repository to /usr/share/X11/xorg.conf.d/20-intel.conf
It didn't work after rebooting, so afterwards I used the "lazy fix":

`cd /tmp`
`wget https://github.com/linuxenko/ubuntu-skylake-i915-video-fix/releases/download/v1/20-intel.conf`
`sudo cp 20-intel.conf /usr/share/X11/xorg.conf.d/20-intel.conf`

Well, after rebooting, my Linux Mint wouldn't start up. It'd just show a black screen and stay there. I can start up into recovery mode and Cinnamon will crash and go into Fallback mode.

Is there anyway I can undo whatever damage I've done to my system?

**Comment by linuxenko** [comment]
You can remove it like so:

`sudo rm /usr/share/X11/xorg.conf.d/20-intel.conf`

**Comment by southhill773** [comment]
Thank you very much. I'm back to normal. I guess I'll just install another video player.
