### ISSUE TITLE
Test on 4.4.3

### ISSUE THREAD

**Issue by linuxenko** [linuxenko/ubuntu-skylake-i915-video-fix#3]
Lets test 4.4.3 kernel on skylake intel cpu based graphic card.

http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.4.3-wily/

**Comment by linuxenko** [comment]
Installation warning

```
W: Possible missing firmware /lib/firmware/i915/skl_guc_ver4.bin for module i915
```

**Comment by maravento** [comment]
W: Possible missing firmware /lib/firmware/i915/skl_guc_ver6.bin for module i915_bpo
